### ISSUE TITLE
Ubuntu/Debian Startup Question

### ISSUE THREAD

**Issue by broguinn** [superrm11/ledmatrix_widgets#9]
Thanks for putting this repo together - super cool. I can get the executable running manually no problem - looks great. However, I can't seem to get it to run on startup. I have this `~/.config/autostart/ledmatrix_widgets.desktop` file:

```
[Desktop Entry]
Type=Application
# tried adding some sleep time to see if the issue is with the matrix being unavailable immediately on startup
Exec=/bin/bash -c "sleep 15 && /usr/bin/ledmatrix_widgets"
# also tried like this:
# Exec=/usr/bin/ledmatrix_widgets
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=LED Matrix Widgets
Name=LED Matrix Widgets
Comment[en_US]=https://github.com/superrm11/ledmatrix_widgets
Comment=https://github.com/superrm11/ledmatrix_widgets
```

It could very well be that my issue is with how I'm setting up this startup script, and might have nothing to do with the peculiarities of this Framework hardware, though my hope is that you have some experience here that might help me get this working on startup. Thanks again!

**Comment by superrm11** [comment]
I'm not too familiar with how ~/.config/autostart works, but I believe it's behavior is defined by the desktop environment / session manager your using, and would need to also be enabled in kde/gnome/somewhere to work. For me, I installed cronie, used `crontab -e` and input `@reboot ledmatrix_widgets`. This makes it run on startup

**Comment by broguinn** [comment]
That worked like a charm - thanks so much. This Framework laptop is the first time I've had Linux as my daily driver, so I really appreciate the help.
